### ISSUE TITLE
How about making an npm/amd-free version?

### ISSUE THREAD

**Issue by stratboy** [KidkArolis/location-bar#10]
:)

Regards

**Comment by KidkArolis** [comment]
You can already install it via npm and `require('location-bar')` in node. Or do you mean something else?

**Comment by stratboy** [comment]
:) Excuse me, I mean the exact opposite: I mean without npm, amd, requirejs and the like. Currently, it will search for a module entity, as pointed out by a previous user.

Anyway, I already have stripped out the amd code from my local version and curretly using. So thank you for your work. Simply, it would be nice to also find a versioned version of this amd/npm-free flavour. So a version one can use just by direct linking or by merging in other parent js files with some compilator like codekit or the like, just as I'm curretly doing.

Thank you again, regards








Karolis Narkevicius wrote:
