### ISSUE TITLE
A way to say if a change event comes from a popstate?

### ISSUE THREAD

**Issue by stratboy** [KidkArolis/location-bar#11]
Hi, I'm finding myself in need to determine if a change event was issued by browser's back/forward, or, in other words, on a popstate event. Is there any way?

**Comment by KidkArolis** [comment]
As opposed to when triggered by calling `location.update()`? Currently there is no way to differentiate. What's your use case? It might be possible to add, on the other hand I'm trying to keep the API as similar to Backbone's as possible for the sake of simplicity..

**Comment by stratboy** [comment]
Since the onchange event fires always, while the window.onpopstate will fire only well, onpopstate, if you need to call a function only onpopstate, you'll giung to have problems.

For example, consider a product category page, with checkbox filters. Consider this workflow:

- the user click the filter, the filter button gains an 'active' class

- the program checks what are the activated filters, and based on then, builds a route url

- the program updates the url via LocationBar.update

- the program does a new query and shows new products

- the user clicks the browser's back button. So the checkbox of the latest filter is not deactivated by a click, it must be deactivated by the program, say, a set_active_filters(). set_active_filters() works getting the information on the active filters by reading the browser's location.

- I could call set_active_filters() onchange. But since onchange also happens because of an url change, that happens because of the user click and thus a manually activated filter, when not triggered during an onpopstate event, in fact set_active_filters will activate already activated buttons. So I want to call set_active_filters only onpopstate. Also, the thing is: onchange is always called BEFORE onopostate. So I cannot check anything from onchange.

A way is to set a 'global' variable, and then use a simple setTimeout function, like this (pieces of code from my product class taken from inside varius functions, so not to use exactly as written, but just to bring you the basic idea):

```javascript

      window.onpopstate = function(e){
        this.was_popstate = true;
      }.bind(this);

      this.location_bar.onChange(function(path){
        this.check_popstate().done(function(is_popstate){
          if(is_popstate){
            this.get_query(true); //will also set_active_filters()
          } else {
            this.get_query(false);
          }
        }.bind(this));
      }.bind(this));

    ,check_popstate:function(){
      var d = $.Deferred();
      setTimeout(function(){
        if(this.was_popstate){
          this.was_popstate = null;
          d.resolve(true);
        }
        d.resolve(false);
      }.bind(this), 100);
      return d.promise();
    }
```

**Comment by KidkArolis** [comment]
I don't know if it helps, but you can use `trigger: false` option like so `locationBar.update("/some/url", {trigger: true})` to avoid getting onChange called when you manually update the URL. This way, onChange only gets called when back/forward is used.

In general though, I would recommend to try and architect the app with unidirectional data flow in mind. 

```
Click a filter in the UI       +-----------------+
                                                 |
                                                 |
Click back/forward             +-----------------------> locationBar.update(...)
                                                 |
                                                 |                +
Open a new tab with some filters in the URL   +--+                |
                                                                  |
                                                                  |
                                                                  |
                                                                  v

                                          locationBar.onChange(function () {renderApp(filters)})

```

The UI updates URL, that triggers change, that refetches data and rerenders. It shouldn't matter if the url change originated from back/forward or from the UI interaction.

I hope this helps.

**Comment by stratboy** [comment]
The trigger false could help, and also thank you for your advice on the app setup. Have a nice day!




Karolis Narkevicius wrote:
