### ISSUE TITLE
Calling route() after .start() should call callback if match exists

### ISSUE THREAD

**Issue by raybooysen** [KidkArolis/location-bar#6]
Is this possible to implement?

If you call .start() and then call .route() n times later, it would be nice if the route regexes match, then the callbacks are fired to get initial state.

**Comment by KidkArolis** [comment]
Interesting. What's your use case? Some kind of dynamic route loading?

The thing is, I'm trying to keep location-bar as close as possible to the semantics/features of Backbone.History, so I'm not sure if it's good to add such a feature that introduces incompatibility.

One possible workaround could be to call undocumented/private [`loadUrl`](https://github.com/KidkArolis/location-bar/blob/2cab961fc5f1da9e240320cfac9f262d86876e64/location-bar.js#L236-L244) method. So you could do something like:

```js
locationBar.start()
locationBar.route(/\/one/, cb1)
locationBar.route(/\/two/, cb2)
locationBar.loadUrl()
```

That would recheck your handlers, including newly added ones and call the callback. However, in this case it will also call the previously defined routes if that's what matches the current URL.

**Comment by raybooysen** [comment]
The use case is that many modules may register an interest in a route during the running of the application.  I don't know up front, which modules will run as this is dynamic.

**Comment by KidkArolis** [comment]
But wouldn't you always execute `start()` only after first defining routes with `route()`?
In other words, you'll 

```
create instance 1
route()
route()
start()

create instance 2
route()
route()
start()
```

start is local to the instance

**Comment by KidkArolis** [comment]
Meant to post this on #5.
