### ISSUE TITLE
location-bar.js:336 Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by fahimbabarpatel** [KidkArolis/location-bar#9]
Hello @KidkArolis ,

I do below steps
1. bower install location-bar
2. Moved my bower_components folder in public folder
3. Added script tag in main layout
   script(src='/bower_components/location-bar/location-bar.js')

When I load page then getting below error in browser console.

location-bar.js:336 Uncaught ReferenceError: module is not defined
anonymous function) @   location-bar.js:336
(anonymous function)    @   location-bar.js:8
(anonymous function)    @   location-bar.js:336

Please guide where I going wrong.

Thanks!

**Comment by KidkArolis** [comment]
Hi, I'm afraid this package only supports AMD or CJS environment. That is you need to be using something like Require.js, Curl.js, webpack or browserify and do `require('location-bar')`. It doesn't export global style - I haven't used that in years myself, and I don't recommend it, which is the main reason why.

You could tweak the code a bit in your project if you'd' like. Replace the last line with:

```js
})(function (factory) { window.LocationBar = factory(); });
```

and then you can access `window.LocationBar`
